// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pet.Api.Models;

#nullable disable

namespace Pet.Api.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20240226094025_InitContext")]
    partial class InitContext
    {
        /// <inheritdoc />
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "8.0.2")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 63);

//             NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
// #pragma warning restore 612, 618
//         }
    }
}
